language: android
jdk: oraclejdk7

android:
   components:
   - build-tools-23.0.2
   - android-23
   - platform-tools
   - extra-android-support
   - extra-google-m2repository
   - extra-android-m2repository

notification:
   email: false

before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo yes | android update sdk --no-ui --all --filter android-23

script:
    - ./gradlew clean build
