language: android
android:
   components:
   - platform-tools
   - android-23
   - build-tools-23.0.1
   - extra-android-m2repository

jdk: oraclejdk7

notification:
   email: false

before_install:
   - sudo apt-get update -qq
   - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
   - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
